version: '3.7'

services:
  gpt_whisper_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_SCRIPT: gpt_whisper_bot.py
    container_name: cont-telegram-whisper-bot
    image: img-telegram-whisper-bot
    restart: unless-stopped
    env_file: gpt_whisper_bot.env

  notes_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_SCRIPT: notes_bot.py
    container_name: cont-telegram-notes-bot
    image: img-telegram-notes-bot
    restart: unless-stopped
    env_file: notes_bot.env


  dev_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_SCRIPT: dev_bot.py
    container_name: cont-telegram-dev-bot
    image: img-telegram-dev-bot
    restart: unless-stopped
    env_file: dev_bot.env


  sleep_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_SCRIPT: sleep_bot.py
    container_name: cont-telegram-sleep-bot
    image: img-telegram-sleep-bot
    restart: unless-stopped
    env_file: sleep_bot.env

  workout_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_SCRIPT: workout_bot.py
    container_name: cont-telegram-workout-bot
    image: img-telegram-workout-bot
    restart: unless-stopped
    env_file: workout_bot.env
    networks:
      - default
      - docker-services-network

  food_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_SCRIPT: food_bot.py
    container_name: cont-telegram-food-bot
    image: img-telegram-food-bot
    restart: unless-stopped
    env_file: food_bot.env
    networks:
      - default
      - docker-services-network

networks:
  docker-services-network:
    external: true
